# Generated by Django 3.2.11 on 2022-02-05 20:07

import datetime
from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deed',
            fields=[
                ('address', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('publisher', models.CharField(default='', max_length=200)),
                ('year', models.IntegerField(default=0)),
                ('volume', models.IntegerField(default=0)),
                ('pos', models.IntegerField(default=0)),
                ('deed_type', models.CharField(default='', max_length=200)),
                ('title', models.CharField(default='', max_length=2000)),
                ('status', models.CharField(default='', max_length=200)),
                ('display_address', models.CharField(default='', max_length=200)),
                ('promulgation', models.DateField(blank=True, default=datetime.date(1, 1, 1))),
                ('announcement_date', models.DateField(blank=True, default=datetime.date(1, 1, 1))),
                ('change_date', models.DateTimeField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc))),
                ('eli', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SearchIsap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(default='', max_length=2000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('query', 'user')},
            },
        ),
        migrations.CreateModel(
            name='DeedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc))),
                ('seq', models.IntegerField(default=0)),
                ('text', models.TextField(default='')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('deed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isap.deed')),
            ],
        ),
        migrations.CreateModel(
            name='SearchIsapResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_run_ts', models.DateTimeField(auto_now_add=True)),
                ('last_run_ts', models.DateTimeField(auto_now=True)),
                ('result', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isap.searchisap')),
            ],
            options={
                'unique_together': {('search', 'result')},
            },
        ),
        migrations.AddIndex(
            model_name='deedtext',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='isap_deedte_search__99edb9_gin'),
        ),
    ]
