# Generated by Django 3.2.11 on 2022-02-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchisapresult',
            name='result_md5',
            field=models.CharField(default='', editable=False, max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='searchisapresult',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='searchisapresult',
            constraint=models.UniqueConstraint(fields=('search', 'result_md5'), name='search_isap_result_md5_uniq'),
        ),
    ]
