# Generated by Django 3.2.11 on 2022-02-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isap', '0002_auto_20220206_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchisap',
            name='first_run_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchisap',
            name='last_run_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
