# Generated by Django 3.2.11 on 2022-02-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isap', '0003_auto_20220207_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchisapresult',
            name='first_run_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchisapresult',
            name='last_run_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
