# Generated by Django 3.2.10 on 2022-01-16 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("isap", "0003_add_polish_fts_config"),
    ]

    operations = [
        migrations.RunSQL(
            sql="create index isap_deedtext_search_vector_index on isap_deedtext using gin (search_vector);",
            reverse_sql="drop index isap_deedtext_search_vector_index;",
        )
    ]
