# Generated by Django 3.2.11 on 2022-02-08 09:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('isap', '0004_auto_20220207_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchisap',
            name='last_run_ts',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc), null=True),
        ),
    ]
