# Generated by Django 3.2.10 on 2022-01-17 10:58

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isap', '0004_add_index_search_vector'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='deedtext',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='isap_deedte_search__99edb9_gin'),
        ),
    ]
