# Generated by Django 3.2.11 on 2022-01-25 07:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('isap', '0005_deedtext_isap_deedte_search__99edb9_gin'),
    ]

    operations = [
        migrations.AddField(
            model_name='deedtext',
            name='change_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc)),
        ),
    ]
