# Generated by Django 3.2.11 on 2022-02-08 11:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('isap', '0006_add_polish_fts_postgersql'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchisapresult',
            name='first_run_ts',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='searchisapresult',
            name='last_run_ts',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0, tzinfo=utc)),
        ),
    ]
