# Generated by Django 3.2.11 on 2022-02-04 06:41

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('isap', '0006_deedtext_change_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('query', models.CharField(default='', max_length=2000, primary_key=True, serialize=False)),
                ('first_run_ts', models.DateTimeField()),
                ('last_run_ts', models.DateTimeField()),
                ('result', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
