# Generated by Django 3.2.11 on 2022-02-04 06:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('isap', '0007_search'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Search',
            new_name='SearchIsap',
        ),
    ]
