# Generated by Django 3.2.11 on 2022-02-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isap', '0007_auto_20220208_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchisap',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
