# Generated by Django 3.2.11 on 2022-02-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isap', '0008_searchisap_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='deedtext',
            name='title',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
