# Generated by Django 4.2.17 on 2025-08-04

from django.db import migrations


def remove_newsletter_artifacts(apps, schema_editor):
    # Find and remove SearchISAP records with subscribed=True
    SearchISAP = apps.get_model('isap', 'SearchISAP')
    SearchISAP.objects.filter(subscribed=True).delete()
    
    # Remove 'subscribed' column if it exists
    try:
        schema_editor.remove_field(SearchISAP, 'subscribed')
    except Exception:
        pass


def remove_user_registration_artifacts(apps, schema_editor):
    try:
        # Remove UserSignupForm if it exists
        UserSignupForm = apps.get_model('users', 'UserSignupForm')
        UserSignupForm.objects.all().delete()
    except Exception:
        pass

    try:
        # Remove UserSocialSignupForm if it exists
        UserSocialSignupForm = apps.get_model('users', 'UserSocialSignupForm')
        UserSocialSignupForm.objects.all().delete()
    except Exception:
        pass


class Migration(migrations.Migration):
    dependencies = [
        ('isap', '0009_deedtext_title'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(remove_newsletter_artifacts),
        migrations.RunPython(remove_user_registration_artifacts),
    ]