# Generated by Django 3.2.11 on 2022-02-02 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False)),
                ('activation_token', models.CharField(default='', max_length=200)),
                ('activation_action_ts', models.DateTimeField(blank=True, null=True)),
                ('activation_email_sent_ts', models.DateTimeField(blank=True, null=True)),
                ('deactivation_ts', models.DateTimeField(blank=True, null=True)),
                ('last_email_sent_ts', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
